spring.application.name=hackaton

# Banco de dados remoto SQL Server
spring.datasource.remote.url=${SPRING_DATASOURCE_REMOTE_URL}
spring.datasource.remote.username=${SPRING_DATASOURCE_REMOTE_USERNAME}
spring.datasource.remote.password=${SPRING_DATASOURCE_REMOTE_PASSWORD}
spring.datasource.remote.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.open-in-view=false